# Generated by Django 4.1.7 on 2023-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='number',
            field=models.SmallIntegerField(auto_created=True, unique=True),
        ),
    ]
