# Generated by Django 4.1.7 on 2023-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_created_at_album_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumitem',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
