name: Music API CI

on: [push]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_DB: netflix
          POSTGRES_USER: james
          POSTGRES_PASSWORD: projectpassword
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
#      - name: Install psycopg2-binary
#        run: pip install psycopg2-binary
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run test
        run: python manage.py test
